### ISSUE TITLE
Application entry file "dist-electron\main\index.js" in the "D:\PhpstormProjects\vite-electron-plugin\release\0.0.0\win-unpacked\resources\app.asar" does not exist.

### ISSUE THREAD

**Issue by developer-av** [electron-vite/vite-electron-plugin#25]
[vite-electron-plugin](https://github.com/electron-vite/vite-electron-plugin)/[examples](https://github.com/electron-vite/vite-electron-plugin/tree/main/examples)/quick-start/

error on build

```
⨯ Application entry file "dist-electron\main\index.js" in the "D:\PhpstormProjects\vite-electron-plugin\release\0.0.0\win-unpacked\resources\app.asar" does not exist. Seems like a wrong configuration.
  failedTask=build stackTrace=Error: Application entry file "dist-electron\main\index.js" in the "D:\PhpstormProjects\vite-electron-plugin\release\0.0.0\win-unpacked\resources\app.asar" does not exist. 
Seems like a wrong configuration.
    at error (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:7:12)
    at Object.checkFileInArchive (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\asar\asarFileChecker.ts:31:11)
    at WinPackager.checkFileInPackage (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\platformPackager.ts:503:7)
    at WinPackager.sanityCheckPackage (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\platformPackager.ts:551:5)
    at WinPackager.doPack (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\platformPackager.ts:312:5)
    at WinPackager.pack (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\platformPackager.ts:136:5)
    at Packager.doBuild (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\packager.ts:441:9)
    at Object.executeFinally (D:\PhpstormProjects\vite-electron-plugin\node_modules\builder-util\src\promise.ts:12:14)
    at Packager._build (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\packager.ts:376:31)
    at Packager.build (D:\PhpstormProjects\vite-electron-plugin\node_modules\app-builder-lib\src\packager.ts:337:12)
    at Object.executeFinally (D:\PhpstormProjects\vite-electron-plugin\node_modules\builder-util\src\promise.ts:12:14)
```

**Comment by caoxiemeihao** [comment]
![Uploading image.png…]()
